config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/cart' => 'cart#index'
  
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'

  
  resources :products

  get '/product_path' => 'product#index'

  root 'page#home'

  get 'page/about'

  get 'page/faqs'

  get 'page/contact'

  

end

app/models/product.rb
class Product < ActiveRecord::Base

	validates :title, :description, :image_url, presence:true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :title, uniqueness: true
	validates :image_url, allow_blank: true, format: { with: %r{\.(gif|jpg|png)\Z}i, 
	message: 'must be a url for GIF, JPG or PNG image.'}

	def index

	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  
  before_action :authenticate_user!, except: [:index]


  def add
  	id = params[:id]
  	 if session[:cart] then
  	 	cart = session[:cart]
  	 else
  	 	session[:cart] = {}
  	 	cart = session[:cart]
  	 end
  	 if cart[id] then
  	 	cart[id] = cart[id] + 1
  	 else
  	 	cart[id] = 1
  	 end
  	 redirect_to :action => :index
  end #end add method

  	def clearCart
  		session[:cart] = nil
  		redirect_to :action => :index
    end
  	def index
  		if session[:cart] then
  			@cart = session[:cart]
  		else
  			@cart = {}
  		end
	end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  
	before_action :authenticate_user!, only: [:contact]

  def home
  end

  def about
  end

  def faqs
  end

  def contact
  end

  def vitamin
  end

  def babycare
  end

  def personelcare
  end

  def analgesics
  end

  def coldremedies
  end

  def beauty
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
  	if params[:category]
  		@products = Product.where(:category=>params[:category])
	  	if @products.empty?
	      flash[:error] = "There are #{@products.count} in this category".html_safe
	    else
	    	flash[:notice] = "There are #{@products.count} in this category".html_safe
	    end    
  	else
    	@products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price, :category, :subcategory)
    end
    
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/index.html.erb
<h1>Your Cart</h1>
	
	<br>

	<% if @cart.empty? %>
	<p> Your cart is empty <p>
	<% else %>
		<%= link_to 'Empty Your Cart', cart_clear_path %> 
		<% end %>
		<br><br><br>
	
<div id="cart product">
	<div class="large-8 columns">

	<% total = 0 %>
	
	
		<% @cart.each do | id, quantity | %>
			<% product = Product.find_by_id(id) %>
			
			<% if product.present? %>
				
				<%= link_to product.title, product %>
				<p><%= product.description %></p>
				<p><%= image_tag(product.image_url) %></p>
			
				<p><%= number_to_currency(product.price, :unit => '$') %></p>
				<p>Quantity: <%= quantity %></p>
				
				<p><% total += quantity * product.price %></p>	
					
			<% end %>
			
		<% end %>
	
		<p><b>Grand Total: <%= number_to_currency(total, :unit => '$')%></b></p>

		</div>
	</div>
		
	
		
			
		
		
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

<div id="topnav">
  <div class="row">
  
    <div id="hours" >
      <div class="large-3 columns">
      <h3>Pharmacy Hours</h3><br>
      <p>Mon - Sat  9.00 AM - 7.00 PM</p>
      <p>Sun and Holidays 10 - 5 PM</p>
      </div>
    </div>
    <div id="katz" align="center" >
      <div class="large-6 columns" >
    <br><br>
      <h1><b>KATZ DRUGS</b></h1>
      </div>
    </div>
    <div id="pay" align="right" >
      <div class="large-3 columns">
      <%= image_tag ('paypal.gif') %>
      </div>
    </div>
  </div>
</div>
  <div id="nav">
    <div id="page_nav">
      <%= link_to 'Home', root_path %>
      <%= link_to 'Shop', products_path %>
      <%= link_to 'About', page_about_path %>
      <%= link_to 'FAQ', page_faqs_path %>
      <%= link_to 'Contact', page_contact_path %>
    </div>

    <div id="sign_in">
      <% if user_signed_in? %>
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign In', new_user_session_path %>
        <%= link_to 'Sign Up', new_user_registration_path %>

      <% end %>
      <%= link_to 'cart', cart_path %>
      
    </div>
  </div>
  <div id="main_wrap">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

      <%= yield %>
  </div>
    
  </body>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/contact.html.erb
<h1>contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

<body>
	
   
       
  
      <div class="row">
        <div class="large-3 columns">
          <h1><img src="http://placehold.it/400x100&text=Logo"/></h1>
        </div>
        <div class="large-9 columns">
          <ul class="inline-list right">
            <li><a href="#">Section 1</a></li>
            <li><a href="#">Section 2</a></li>
            <li><a href="#">Section 3</a></li>
            <li><a href="#">Section 4</a></li>
          </ul>
        </div>
      </div>
      
       
      
      
      <div class="row">    
        
         
         
        <div class="large-9 push-3 columns">
          
          <h3>Page Title <small>Page subtitle</small></h3>
          
          <p>Bacon ipsum dolor sit amet salami ham hock biltong ball tip drumstick sirloin pancetta meatball short loin. Venison tail chuck pork chop, andouille ball tip beef ribs flank boudin bacon. Salami andouille pork belly short ribs flank cow. Salami sirloin turkey kielbasa. Sausage venison pork loin leberkas chuck short loin, cow ham prosciutto pastrami jowl. Ham hock jerky tri-tip, fatback hamburger shoulder swine pancetta ground round. Tri-tip prosciutto meatball turkey, brisket spare ribs shankle chuck cow chicken ham hock boudin meatloaf jowl.</p>
     
          <p>Ground round pastrami pork loin tenderloin jerky. Jerky spare ribs biltong, ham hock ham capicola pork. Jerky turducken pork, meatloaf sausage capicola swine corned beef turkey short loin. Tongue prosciutto pork loin, ground round spare ribs venison kielbasa strip steak.</p>
     
          <p>Hamburger bresaola turkey t-bone, leberkas salami pork chop ham hock beef ribs. Rump biltong meatball venison, short ribs pork loin shank shankle corned beef beef. Cow salami jowl short loin hamburger fatback. Short ribs pork belly shoulder pastrami drumstick salami corned beef ham hock bresaola. Swine filet mignon cow sausage ball tip. Cow ribeye ground round, sausage pork loin pig beef ball tip turkey boudin.</p>
     
          <p>Prosciutto ball tip filet mignon andouille frankfurter chicken rump sausage meatball. Filet mignon meatloaf ground round andouille ham hock pork. Bresaola short loin meatball chuck hamburger pig. Turkey venison chuck, tongue fatback tail swine jerky corned beef shank kielbasa prosciutto ribeye ham tri-tip. Rump bacon pork belly meatloaf shoulder short loin meatball kielbasa pork loin tongue bresaola brisket corned beef jowl prosciutto. Beef ribs shankle short ribs pork belly corned beef fatback pork chop tongue biltong boudin strip steak sirloin meatloaf pancetta.</p>
                
        </div>
        
        
         
         
        <div class="large-3 pull-9 columns">
            
          <ul class="side-nav">
            <li><a href="#">Section 1</a></li>
            <li><a href="#">Section 2</a></li>
            <li><a href="#">Section 3</a></li>
            <li><a href="#">Section 4</a></li>
            <li><a href="#">Section 5</a></li>
            <li><a href="#">Section 6</a></li>
          </ul>
          
          <p><img src="http://placehold.it/320x240&text=Ad"/></p>
            
        </div>
        
      </div>
        
      
       
      
      <footer class="row">
        <div class="large-12 columns">
          <hr/>
          <div class="row">
            <div class="large-6 columns">
              <p>© Copyright no one at all. Go to town.</p>
            </div>
            <div class="large-6 columns">
              <ul class="inline-list right">
                <li><a href="#">Section 1</a></li>
                <li><a href="#">Section 2</a></li>
                <li><a href="#">Section 3</a></li>
                <li><a href="#">Section 4</a></li>
              </ul>
            </div>
          </div>
        </div> 
      </footer>


	
</body>

app/views/page/faqs.html.erb
<h1>FAQ</h1>
<p>Find me in app/views/page/faqs.html.erb</p>

app/views/page/home.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title>Cartapp</title>
  		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  		<%= csrf_meta_tags %>
	</head>
	<body>	

		<div class="row">
			
			  <div class="small-4 columns">
			    <h2 class="subheader"><b><font color='blue'</font>KATZ DRUGS PHARMACY</b></h2>
			     
			    <br><br>
				<p>Was established in 1889, Growing and changing at a dramatic pace,
				today <b>KATZ DRUGS PHARMACY</b> is one of the largest and most experienced Independent Pharmacies in Brooklyn New York.
				Our team of pharmacists and well trained and qualified professionals are reliable, and always willing to assist you with all your prescriptions and health related questions.
				we believe in maintaining the traditional and personalized old fashioned customer service to gladly help with every healthcare need.</p>
		  		</div>
		  	<%= image_tag ('Surf.jpg') %>
		</div>
	</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :subcategory %><br>
    <%= f.text_field :subcategory %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>


      <div class="row">
      <div class="large-10 columns">


          <ul data-orbit
              data-options="animation:slide;
                            pause_on_hover:true;
                            animation_speed:1500;
                            navigation_arrows:false;
                            bullets:false;
                            speed: 800:
                            align: center">
           
            <li class="active" width: 1000>
              <%= image_tag("perfume1.jpg")%>
              <div class="orbit-caption">
                Perfume.
              </div>
            </li>
            <li class="active" width: 1000>
              <%= image_tag("Cologne1.jpg")%>
              <div class="orbit-caption">
                Cologne.
              </div>
            </li>
            <li class="active" width: 1000>
              <%= image_tag("cologne5.jpg")%>
              <div class="orbit-caption">
                Three.
              </div>
            </li>
          </ul>
       </div> 
          
      <div class="row">    
        <div class="large-9 push-3 columns">
          <%= @myimage1 %>


            <table>

                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Product Image</th>
                    <th>Price</th>
                    <th colspan="3"></th>
                  </tr>
                </thead>

                <tbody>
                      
                    <% @products.each do |product| %>
                      
                      <tr>
                        <td><%= product.title %></td>
                        <td><%= product.description %></td>
                        <td><%= image_tag (product.image_url), :size => '100x100'  %></td>
                        <td><%= product.price %></td>

                        <td><a href="/cart/<%= product.id %>" class="button round tiny radius" > Add to Cart</a></td>
                      </tr>
                    <% end %>
          </div>
    
          </tbody>
          </table>

          <br>
        </div>
        <div class="large-3 pull-9 columns">
            
          <ul class="side-nav">
            <li> <%= link_to "All Products", products_path %> </li>
            <li> <%= link_to "Beauty", products_path(:category=>"Beauty Products") %> </li>
            <li> <%= link_to "Perfumes", products_path(:category=>"perfumes") %> </li>
            <li> <%= link_to "Eye Care Products", products_path(:category=>"Eye Care Products") %> </li>
            <li> <%= link_to "Diabetes Care", products_path(:category=>"Diabetes Care") %> </li>
            <li> <%= link_to "Analgesics", products_path(:category=>"Analgesics") %> </li>
            <li> <%= link_to "Personel Care", products_path(:category=>"Personel Care") %> </li>

          </ul>
          
          <p><%= image_tag("Glucose meters.jpg")%></p>
            
        </div>
        
        </div>
        <%= link_to 'New Product', new_product_path %>
        
      <footer class="row">
        <div class="large-12 columns">
          <hr/>
          <div class="row">
            <div class="large-6 columns">
              <p>© Copyright no one at all. Go to town.</p>
            </div>
            <div class="large-6 columns">
              <ul class="inline-list right">
                <li><a href="#">Prescriptions</a></li>
                <li><a href="#">vitamins</a></li>
                <li><a href="#">Cosmetics</a></li>
                <li><a href="#">Personel Care</a></li>
              </ul>
            </div>
          </div>
        </div> 
      </footer>
   
</body>
</html>
                
        

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<h1>THIS IS MY PRODUCT</h1>
<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Subcategory:</strong>
  <%= @product.subcategory %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>